### ISSUE TITLE
PD Module Milestones

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#83]
**Background**

In order for trainees to take PD seriously and actually do the work that volunteers put so much effort in we need to set milestones. Similar to Module success, we need to set some limits and set repercussions if those aren't met in a certain time frame. 

**Acceptance criteria**

- [ ] Breakdown in smaller sections
- [ ] Define the milestones
- [ ] Define the time frames

**Responsible** 

- @CodeYourFuture/pd-syllabus-team 

**Stakeholders**

- @LaraHuzjan 
- @kfklein15 

**Aproovers**

- @kfklein15
